### PR TITLE
Add multi-select mode

### PR DESCRIPTION
**Pull request by hansmansson**
Enter multi-select mode by pressing tab, do selections and then press tab again to exit and run action.

### CODE REVIEW

**Comment by hansmansson** [comment]
Thanks you @abhinav for this project. Nice and clean code, so adding this was fairly easy.
Glad to hear you liked the addition, I'll see if I can add deselection support.

**Comment by hansmansson** [comment]
Now you can de-select a selected match by retyping the hint-label, which is also highlighted now. This also shrank the size of the pull request as I understood I did thing in a inefficient way.

**Comment by abhinav** [comment]
This looks great! I've made some tweaks. Namely:

- The deselection label is dark red. So it looks like the regular red label, except a bit grayed out.
- Pressing Enter in multi-select mode also accepts what you've picked so far.

**Comment by abhinav** [comment]
Thanks! I'll take a stab at documenting this before tagging a release.

**Pull request merged**
